#!/usr/bin/env python3

import sys

label = ""
lines = []
ok = True
for line in sys.stdin:
    line = line.strip()
    if line == "":
        if ok:
            sys.stdout.write("\n".join(lines) + "\n\n")
        ok = True
        lines = []
        continue
    lines.append(line)
    if line.startswith("# source ="):
        label = line.split()[3]
    else:
        aa = line.split("\t")
        if aa[0].find(".") > -1:
            continue
        if len(aa) == 10:
            try:
                v = int(aa[6])
            except:
                ok = False
                sys.stderr.write(label + "\n")

        
