#
# Use this if you don't have textXPath available:
#
#     make -f Makefile.build
#
# This will ignore any updates in files with names ending with: -in.go
#

SRC = \
	auxiliary.go \
	conllu.go \
	depheads.go \
	deplabels.go \
	deprels.go \
	document.go \
	emptyheads.go \
	enhanced.go \
	features.go \
	fixpunct.go \
	helpers.go \
	main.go \
	misplacedheads.go \
	postags.go \
	xpath.go \
	untokenize.go \



all: unidep

unidep: $(SRC)
	go build -o $@ $^
